steps:
  - label: ":junit: Unit Tests"
    agents:
      queue: test-builder
    plugins:
      Widen/gradle#v1:
        buildImage: quay.io/widen/corretto-java-11-gradle:gradle8.12-2025-r1
        tasks: check

  - wait

  - label: ":gradle: Publish Plugin"
    command: ".buildkite/publish.sh"
    branches: "*.*.*"
    agents:
      queue: builder
    plugins:
      Widen/gradle#v1:
        buildImage: quay.io/widen/corretto-java-11-gradle:gradle8.12-2025-r1
